.eqv size 9

.data
vetor:  .word 10,9,8,7,6,5,4,3,2,1

.text	
MAIN:
	//**********
	//X1 -> ENDEREÇO DO VETOR
	//X2 -> CONTADOR
	//X3 -> ELEMENTO N
	//X4 -> ELEMENTO N+1
	//X5 -> RESULTADO DA SUBTRAÇÃO
	//X6 -> FLAG DE NEGATIVO
	//X7 -> FLAG SE HOUVE TROCA
	//X8 -> AUX
	//**********
	
	//ADD X1, XZR, XZR
	LDA X1, vetor
	ADDI X2, XZR, size
	
	ADD X7, XZR, XZR
	
LOOP:
	
	LDUR X3, [X1, 0] //CARREGO N
	//LDUR X4, [X1, 8] //CARREGO N+1
	LDUR X4, [X1, 4] //CARREGO N+1
	
	
	SUB X5, X3, X4 //SUBTRAIO N+1 DE N
	LSR X6, X5, 31 //BUSCO O ÚLTIMO BIT DO RESULTADO
	
	CBZ X6, 5//calcular imediato //SE O ÚLTIMO BIT FOR 0, SIGNIFICA QUE O RESULTADO É POSITIVO -> PRECISAMOS TROCAR

RETLOOP:

//	ADDI X1, X1, 8 //INCREMENTO O ENDEREÇO
	ADDI X1, X1, 4 //INCREMENTO O ENDEREÇO
		
	SUBI X2, X2, 1 //DECREMENTANDO CONTADOR
	
	CBZ X2, 10 //VERIFICANDO SE ESTAMOS NO FINAL DO VETOR
	// SUBI XZR,X2,0
	// B.EQ AUX
	
	B LOOP


SWAP:
	ADD X0, XZR, X3 //COPIO VALOR DE N PARA X0
	
	//ADDI X8, X1, 8	//COPIO O ENDEREÇO DE N+1 PARA X8
	ADDI X8, X1, 4	//COPIO O ENDEREÇO DE N+1 PARA X8
	
	STUR X0, [X8, 0] //SALVO O VALOR DE "N" NO ENDEREÇO DE N+1
	
	ADD X0, XZR, X4 //COPIO O VALOR DE N+1 PARA X0
	
	ADDI X8, X1, 0 //COPIO O ENDEREÇO DE N PARA X8
	
	STUR X0, [X8, 0] //SALVO O VALOR DE "N+1" NO ENDEREÇO DE N
	
	ADDI X7, XZR, 1
	
	B RETLOOP

AUX:	
	SUBI X8, X7, 1
	CBZ X8, 2
	
	B END //VETOR ESTÁ ORDENADO

EXITLOOP:
	
	//ADD X1, XZR, XZR
	LDA X1, vetor
	ADDI X2, XZR, size
	
	B LOOP
	
END:
	ADDI X8,XZR,#10
	SVC 0
	//VETOR ORDENADO
